language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
  - "hhvm"

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install
script:
  - cd tests/
  - ../vendor/bin/phpunit
