language: php

php:
  - "5.3"
  - "5.4"
  - "5.5"
  - "5.6"
  - "hhvm"

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

script:
  - vendor/bin/phpunit -c tests/phpunit.xml tests/

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm