language: php

php:
  - "8.1"

before_script:
  - wget https://getcomposer.org/composer.phar
  - php composer.phar install

script:
  - vendor/bin/phpunit -c tests/phpunit.xml tests/

matrix:
  fast_finish: true