<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'CurrencyExchange\Module'                             => __DIR__ . '/Module.php',
  'CurrencyExchange\Exception\InvalidArgumentException' => __DIR__ . '/src/CurrencyExchange/Exception/InvalidArgumentException.php',
  'CurrencyExchange\Exception\InvalidMethodException'   => __DIR__ . '/src/CurrencyExchange/Exception/InvalidMethodException.php',
  'CurrencyExchange\Exception\ResponseException'        => __DIR__ . '/src/CurrencyExchange/Exception/ResponseException.php',
  'CurrencyExchange\Exchanger'                          => __DIR__ . '/src/CurrencyExchange/Exchanger.php',
  'CurrencyExchange\Methods\AbstractMethod'             => __DIR__ . '/src/CurrencyExchange/Methods/AbstractMethod.php',
  'CurrencyExchange\Methods\GoogleExchangeRate'         => __DIR__ . '/src/CurrencyExchange/Methods/GoogleExchangeRate.php',
  'CurrencyExchange\Methods\GrandTrunk'                 => __DIR__ . '/src/CurrencyExchange/Methods/GrandTrunk.php',
  'CurrencyExchange\Methods\YahooFinance'               => __DIR__ . '/src/CurrencyExchange/Methods/YahooFinance.php',
);
