<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'CurrencyExchange\Module'                             => __DIR__ . '/Module.php',
  'CurrencyExchange\Currency'                           => __DIR__ . '/src/CurrencyExchange/Currency.php',
  'CurrencyExchange\Exception\InvalidArgumentException' => __DIR__ . '/src/CurrencyExchange/Exception/InvalidArgumentException.php',
  'CurrencyExchange\Exception\InvalidMethodException'   => __DIR__ . '/src/CurrencyExchange/Exception/InvalidMethodException.php',
  'CurrencyExchange\Exception\ParseException'           => __DIR__ . '/src/CurrencyExchange/Exception/ParseException.php',
  'CurrencyExchange\Exception\ResponseException'        => __DIR__ . '/src/CurrencyExchange/Exception/ResponseException.php',
  'CurrencyExchange\Exchanger'                          => __DIR__ . '/src/CurrencyExchange/Exchanger.php',
  'CurrencyExchange\HttpClient'                         => __DIR__ . '/src/CurrencyExchange/HttpClient.php',
  'CurrencyExchange\Methods\GoogleExchangeRate'         => __DIR__ . '/src/CurrencyExchange/Methods/GoogleExchangeRate.php',
  'CurrencyExchange\Methods\GrandTrunk'                 => __DIR__ . '/src/CurrencyExchange/Methods/GrandTrunk.php',
  'CurrencyExchange\Methods\MethodAbstract'             => __DIR__ . '/src/CurrencyExchange/Methods/MethodAbstract.php',
  'CurrencyExchange\Methods\WebServiceX'                => __DIR__ . '/src/CurrencyExchange/Methods/WebServiceX.php',
  'CurrencyExchange\Methods\YahooFinance'               => __DIR__ . '/src/CurrencyExchange/Methods/YahooFinance.php',
  'CurrencyExchange\Options'                            => __DIR__ . '/src/CurrencyExchange/Options.php',
  'CurrencyExchange\Service\MethodFactory'              => __DIR__ . '/src/CurrencyExchange/Service/MethodFactory.php',
  'CurrencyExchange\Service\UriFactory'                 => __DIR__ . '/src/CurrencyExchange/Service/UriFactory.php',
  'CurrencyExchange\Uri\UriAbstract'                    => __DIR__ . '/src/CurrencyExchange/Uri/UriAbstract.php',
  'CurrencyExchange\Uri\UriGet'                         => __DIR__ . '/src/CurrencyExchange/Uri/UriGet.php',
  'CurrencyExchange\Uri\UriPost'                        => __DIR__ . '/src/CurrencyExchange/Uri/UriPost.php',
);
