<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'CurrencyExchange\Module'                             => __DIR__ . '/Module.php',
  'CurrencyExchange\Exchanger'                          => __DIR__ . '/src/CurrencyExchange/Exchanger.php',
  'CurrencyExchange\HttpClient'                         => __DIR__ . '/src/CurrencyExchange/HttpClient.php',
  'CurrencyExchange\Currency'                           => __DIR__ . '/src/CurrencyExchange/Currency.php',
  'CurrencyExchange\Service\MethodFactory'              => __DIR__ . '/src/CurrencyExchange/Service/MethodFactory.php',
  'CurrencyExchange\Service\UriFactory'                 => __DIR__ . '/src/CurrencyExchange/Service/UriFactory.php',
  'CurrencyExchange\Methods\GoogleExchangeRate'         => __DIR__ . '/src/CurrencyExchange/Methods/GoogleExchangeRate.php',
  'CurrencyExchange\Methods\YahooFinance'               => __DIR__ . '/src/CurrencyExchange/Methods/YahooFinance.php',
  'CurrencyExchange\Methods\AbstractMethod'             => __DIR__ . '/src/CurrencyExchange/Methods/AbstractMethod.php',
  'CurrencyExchange\Methods\GrandTrunk'                 => __DIR__ . '/src/CurrencyExchange/Methods/GrandTrunk.php',
  'CurrencyExchange\Uri\UriPost'                        => __DIR__ . '/src/CurrencyExchange/Uri/UriPost.php',
  'CurrencyExchange\Uri\UriGet'                         => __DIR__ . '/src/CurrencyExchange/Uri/UriGet.php',
  'CurrencyExchange\Uri\AbstractUri'                    => __DIR__ . '/src/CurrencyExchange/Uri/AbstractUri.php',
  'CurrencyExchange\Exception\ResponseException'        => __DIR__ . '/src/CurrencyExchange/Exception/ResponseException.php',
  'CurrencyExchange\Exception\InvalidMethodException'   => __DIR__ . '/src/CurrencyExchange/Exception/InvalidMethodException.php',
  'CurrencyExchange\Exception\InvalidArgumentException' => __DIR__ . '/src/CurrencyExchange/Exception/InvalidArgumentException.php',
);
